version: '2.0'
services:
  # builds lambda package
  build:
    image: softprops/lambda-rust
    volumes:
    - .:/code
    - $HOME/.cargo/registry:/root/.cargo/registry
    environment:
    - BIN=lambda